/* The following code was generated by JFlex 1.6.1 */

package fr.ubordeaux.deptinfo.compilation.lea.parser;

import java.io.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/mnt/c/Users/yohan/OneDrive/Documents/FAC/L3/Cours semestre 6/Compilation/miniprojet/lexer/Lexer.jflex</tt>
 */
public class ParserLexer implements Parser.Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\60\1\12\1\12\1\12\1\12\23\0\1\26\1\6\2\0"+
    "\1\30\1\31\1\7\1\15\1\16\1\11\1\27\1\23\1\5\1\3"+
    "\1\10\12\2\1\24\1\25\1\21\1\33\1\22\2\0\4\1\1\4"+
    "\25\1\1\17\1\0\1\20\1\0\1\1\1\0\1\40\1\34\1\44"+
    "\1\54\1\37\1\61\1\62\1\45\1\52\1\1\1\43\1\36\1\47"+
    "\1\41\1\35\1\50\1\55\1\42\1\46\1\51\1\53\1\56\1\63"+
    "\1\57\1\64\1\1\1\13\1\32\1\14\7\0\1\12\u1fa2\0\1\12"+
    "\1\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\2\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\1\20\2\2\0\1\30\1\31\1\32\1\0"+
    "\1\33\1\0\1\34\1\0\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\30\2\1\55\1\2\1\56"+
    "\1\57\10\2\2\60\1\0\1\61\1\0\1\62\1\63"+
    "\1\64\1\65\22\2\1\66\2\2\1\67\12\2\1\70"+
    "\5\2\1\34\3\2\1\71\1\72\1\73\2\2\1\74"+
    "\1\75\7\2\1\76\1\77\2\2\1\100\4\2\1\101"+
    "\1\102\14\2\1\103\5\2\1\104\1\105\2\2\1\106"+
    "\15\2\1\107\1\110\1\2\1\111\1\112\4\2\1\113"+
    "\1\114\2\2\1\115\1\116\3\2\1\117\2\2\1\120"+
    "\6\2\1\121\7\2\1\122\1\2\1\123\1\2\1\124"+
    "\1\125\1\126\1\2\1\127\1\130\1\2\1\131\1\132"+
    "\5\2\1\133\2\2\1\134\1\135\1\136\1\2\1\137"+
    "\1\140\1\141";

  private static int [] zzUnpackAction() {
    int [] result = new int[281];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\u01a8\0\u01dd\0\65\0\65\0\65\0\65\0\65\0\65"+
    "\0\u0212\0\u0247\0\65\0\u027c\0\65\0\u02b1\0\u02e6\0\u031b"+
    "\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3"+
    "\0\u04f8\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636\0\u066b"+
    "\0\u06a0\0\u06d5\0\u070a\0\u073f\0\u0774\0\65\0\65\0\65"+
    "\0\u013e\0\65\0\u07a9\0\u07de\0\u0813\0\65\0\65\0\u0848"+
    "\0\65\0\u087d\0\65\0\65\0\65\0\65\0\65\0\65"+
    "\0\u08b2\0\65\0\u08e7\0\65\0\65\0\u091c\0\u0951\0\u0986"+
    "\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e"+
    "\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\u0cd6"+
    "\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\152"+
    "\0\152\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc"+
    "\0\u0ff1\0\u1026\0\u105b\0\u105b\0\65\0\u1090\0\65\0\65"+
    "\0\65\0\65\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce"+
    "\0\u1203\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u1341\0\u1376"+
    "\0\u13ab\0\u13e0\0\u1415\0\u144a\0\152\0\u147f\0\u14b4\0\152"+
    "\0\u14e9\0\u151e\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u165c"+
    "\0\u1691\0\u16c6\0\u16fb\0\u1730\0\u1765\0\u179a\0\u17cf\0\u1804"+
    "\0\65\0\u1839\0\u186e\0\u18a3\0\152\0\152\0\152\0\u18d8"+
    "\0\u190d\0\65\0\152\0\u1942\0\u1977\0\u19ac\0\u19e1\0\u1a16"+
    "\0\u1a4b\0\u1a80\0\152\0\152\0\u1ab5\0\u1aea\0\152\0\u1b1f"+
    "\0\u1b54\0\u1b89\0\u1bbe\0\152\0\152\0\u1bf3\0\u1c28\0\u1c5d"+
    "\0\u1c92\0\u1cc7\0\u1cfc\0\u1d31\0\u1d66\0\u1d9b\0\u1dd0\0\u1e05"+
    "\0\u1e3a\0\152\0\u1e6f\0\u1ea4\0\u1ed9\0\u1f0e\0\u1f43\0\152"+
    "\0\152\0\u1f78\0\u1fad\0\152\0\u1fe2\0\u2017\0\u204c\0\u2081"+
    "\0\u20b6\0\u20eb\0\u2120\0\u2155\0\u218a\0\u21bf\0\u21f4\0\u2229"+
    "\0\u225e\0\152\0\152\0\u2293\0\u22c8\0\152\0\u22fd\0\u2332"+
    "\0\u2367\0\u239c\0\152\0\152\0\u23d1\0\u2406\0\152\0\152"+
    "\0\u243b\0\u2470\0\u24a5\0\152\0\u24da\0\u250f\0\152\0\u2544"+
    "\0\u2579\0\u25ae\0\u25e3\0\u2618\0\u264d\0\152\0\u2682\0\u26b7"+
    "\0\u26ec\0\u2721\0\u2756\0\u278b\0\u27c0\0\152\0\u27f5\0\152"+
    "\0\u282a\0\152\0\152\0\152\0\u285f\0\152\0\152\0\u2894"+
    "\0\65\0\152\0\u28c9\0\u28fe\0\u2933\0\u2968\0\u299d\0\152"+
    "\0\u29d2\0\u2a07\0\152\0\152\0\152\0\u2a3c\0\152\0\152"+
    "\0\152";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[281];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\3\1\6\1\7\1\10"+
    "\1\11\1\12\1\2\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\3\1\40\1\41\1\3\1\42\1\3\1\43\1\44"+
    "\1\45\1\46\1\47\1\3\1\50\1\3\1\51\1\3"+
    "\1\2\1\52\1\3\1\53\1\3\66\0\2\3\1\0"+
    "\1\3\27\0\24\3\1\0\4\3\2\0\1\4\1\54"+
    "\1\55\32\0\1\55\30\0\1\56\66\0\1\57\25\0"+
    "\1\60\31\0\6\61\1\62\56\61\7\63\1\0\55\63"+
    "\10\0\1\64\1\65\21\0\1\66\64\0\1\67\52\0"+
    "\1\70\11\0\1\71\53\0\1\72\10\0\1\73\64\0"+
    "\1\74\64\0\1\75\60\0\1\76\3\0\1\77\64\0"+
    "\1\100\62\0\1\101\1\0\1\102\63\0\1\103\1\104"+
    "\64\0\1\105\32\0\2\3\1\0\1\3\27\0\1\3"+
    "\1\106\4\3\1\107\15\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\14\3\1\110\7\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\16\3\1\111\5\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\2\3"+
    "\1\112\2\3\1\113\13\3\1\114\1\3\1\115\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\3\3\1\116"+
    "\13\3\1\117\4\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\3\3\1\120\1\121\17\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\1\3\1\122\1\123"+
    "\1\3\1\124\4\3\1\125\12\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\3\3\1\126\11\3\1\127"+
    "\6\3\1\0\2\3\1\130\1\3\1\0\2\3\1\0"+
    "\1\3\27\0\4\3\1\131\17\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\6\3\1\132\10\3\1\133"+
    "\4\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\11\3\1\134\12\3\1\0\3\3\1\135\1\0\2\3"+
    "\1\0\1\3\27\0\5\3\1\136\5\3\1\137\10\3"+
    "\1\0\1\140\3\3\1\0\2\3\1\0\1\3\27\0"+
    "\1\3\1\141\1\3\1\142\20\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\16\3\1\143\5\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\1\3\1\144"+
    "\1\145\13\3\1\146\1\147\4\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\6\3\1\150\2\3\1\151"+
    "\12\3\1\0\4\3\2\0\1\152\64\0\1\153\2\0"+
    "\1\154\21\0\1\154\44\0\1\155\55\0\12\64\1\0"+
    "\52\64\11\65\1\156\53\65\33\0\1\157\64\0\1\160"+
    "\64\0\1\161\64\0\1\162\32\0\2\3\1\0\1\3"+
    "\27\0\1\3\1\163\22\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\3\3\1\164\20\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\3\3\1\165\20\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\12\3"+
    "\1\166\11\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\12\3\1\167\11\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\17\3\1\170\4\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\17\3\1\171\4\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\15\3"+
    "\1\172\6\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\24\3\1\0\2\3\1\173\1\3\1\0\2\3"+
    "\1\0\1\3\27\0\2\3\1\174\21\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\4\3\1\175\10\3"+
    "\1\176\6\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\5\3\1\177\16\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\5\3\1\200\5\3\1\201\10\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\4\3"+
    "\1\202\17\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\12\3\1\203\11\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\4\3\1\204\17\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\15\3\1\205\6\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\6\3"+
    "\1\206\15\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\16\3\1\207\5\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\14\3\1\210\1\3\1\211\5\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\1\3"+
    "\1\212\14\3\1\213\5\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\1\214\23\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\16\3\1\215\5\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\14\3\1\216"+
    "\7\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\15\3\1\217\6\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\14\3\1\220\7\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\24\3\1\0\1\221\3\3"+
    "\1\0\2\3\1\0\1\3\27\0\6\3\1\222\15\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\6\3"+
    "\1\223\15\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\1\3\1\224\22\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\5\3\1\225\16\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\5\3\1\226\16\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\16\3"+
    "\1\227\5\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\16\3\1\230\5\3\1\0\4\3\2\0\1\152"+
    "\1\0\1\55\32\0\1\55\27\0\1\153\62\0\10\65"+
    "\1\231\1\156\53\65\1\0\2\3\1\0\1\3\27\0"+
    "\2\3\1\232\21\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\4\3\1\233\17\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\6\3\1\234\15\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\15\3\1\235"+
    "\6\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\3\3\1\236\20\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\13\3\1\237\10\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\16\3\1\240\5\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\3\3\1\241"+
    "\20\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\24\3\1\242\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\2\3\1\243\21\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\20\3\1\244\3\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\17\3\1\245\4\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\24\3\1\0"+
    "\1\3\1\246\2\3\1\0\2\3\1\0\1\3\27\0"+
    "\12\3\1\247\2\3\1\250\6\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\14\3\1\251\7\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\12\3\1\252"+
    "\11\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\3\3\1\253\20\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\6\3\1\254\15\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\16\3\1\255\5\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\15\3\1\256"+
    "\6\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\5\3\1\257\16\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\10\3\1\260\4\3\1\261\6\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\22\3\1\262"+
    "\1\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\2\3\1\263\21\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\12\3\1\264\11\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\3\3\1\265\20\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\3\3\1\266"+
    "\20\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\1\3\1\267\1\270\21\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\4\3\1\271\17\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\15\3\1\272\6\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\3\3"+
    "\1\273\20\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\4\3\1\274\17\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\4\3\1\275\17\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\10\3\1\276\13\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\15\3"+
    "\1\277\6\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\2\3\1\300\21\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\3\3\1\301\20\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\7\3\1\302\14\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\4\3"+
    "\1\303\17\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\22\3\1\304\1\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\5\3\1\305\16\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\2\3\1\306\21\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\6\3"+
    "\1\307\15\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\3\3\1\310\20\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\15\3\1\311\6\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\16\3\1\312\5\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\4\3"+
    "\1\313\17\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\12\3\1\314\11\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\5\3\1\315\16\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\10\3\1\316\13\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\3\3"+
    "\1\317\20\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\3\3\1\320\20\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\4\3\1\321\17\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\16\3\1\322\5\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\6\3"+
    "\1\323\15\3\1\0\1\3\1\324\2\3\1\0\2\3"+
    "\1\0\1\3\27\0\6\3\1\325\15\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\3\3\1\326\20\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\17\3"+
    "\1\327\4\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\17\3\1\330\4\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\4\3\1\331\17\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\15\3\1\332\6\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\2\3"+
    "\1\333\21\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\15\3\1\334\6\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\3\3\1\335\20\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\3\3\1\336\20\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\4\3"+
    "\1\337\17\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\15\3\1\340\6\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\4\3\1\341\17\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\20\3\1\342\3\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\5\3"+
    "\1\343\16\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\5\3\1\344\16\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\5\3\1\345\16\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\6\3\1\346\15\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\24\3"+
    "\1\0\1\3\1\347\2\3\1\0\2\3\1\0\1\3"+
    "\27\0\11\3\1\350\12\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\20\3\1\351\3\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\10\3\1\352\13\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\15\3"+
    "\1\353\6\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\10\3\1\354\13\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\24\3\1\0\1\355\3\3\1\0"+
    "\2\3\1\0\1\3\27\0\3\3\1\356\20\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\15\3\1\357"+
    "\6\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\13\3\1\360\10\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\2\3\1\361\21\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\4\3\1\362\17\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\10\3\1\363"+
    "\13\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\16\3\1\364\5\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\2\3\1\365\21\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\5\3\1\366\16\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\1\3\1\367"+
    "\22\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\2\3\1\370\21\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\12\3\1\371\11\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\17\3\1\372\4\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\4\3\1\373"+
    "\17\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\17\3\1\374\4\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\15\3\1\375\6\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\3\3\1\376\20\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\4\3\1\377"+
    "\17\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\6\3\1\u0100\15\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\3\3\1\u0101\20\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\15\3\1\u0102\6\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\2\3\1\u0103"+
    "\21\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\11\3\1\u0104\12\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\1\3\1\u0105\22\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\5\3\1\u0106\16\3\1\0"+
    "\4\3\1\0\2\3\1\0\1\3\27\0\6\3\1\u0107"+
    "\15\3\1\0\4\3\1\0\2\3\1\0\1\3\27\0"+
    "\3\3\1\u0108\20\3\1\0\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\24\3\1\u0109\4\3\1\0\2\3\1\0"+
    "\1\3\27\0\3\3\1\u010a\20\3\1\0\4\3\1\0"+
    "\2\3\1\0\1\3\27\0\1\u010b\23\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\6\3\1\u010c\15\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\3\3"+
    "\1\u010d\20\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\10\3\1\u010e\13\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\5\3\1\u010f\16\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\5\3\1\u0110\16\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\5\3"+
    "\1\u0111\16\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\2\3\1\u0112\21\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\3\3\1\u0113\20\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\20\3\1\u0114\3\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\3\3"+
    "\1\u0115\20\3\1\0\4\3\1\0\2\3\1\0\1\3"+
    "\27\0\15\3\1\u0116\6\3\1\0\4\3\1\0\2\3"+
    "\1\0\1\3\27\0\15\3\1\u0117\6\3\1\0\4\3"+
    "\1\0\2\3\1\0\1\3\27\0\3\3\1\u0118\20\3"+
    "\1\0\4\3\1\0\2\3\1\0\1\3\27\0\12\3"+
    "\1\u0119\11\3\1\0\4\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10865];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\6\11\2\1\1\11\1\1\1\11"+
    "\26\1\2\0\3\11\1\0\1\11\1\0\1\1\1\0"+
    "\2\11\1\1\1\11\1\1\6\11\1\1\1\11\1\1"+
    "\2\11\46\1\1\0\1\11\1\0\4\11\46\1\1\11"+
    "\10\1\1\11\146\1\1\11\20\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[281];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private final boolean DEBUGGING = false;
  
  private Position startPos = new Position(0, 0);
  private Position endPos = new Position(0, 0);
  private Object lVal;

    /**
     * Method to retrieve the beginning position of the last scanned token.
     * @return the position at which the last scanned token starts.
     */
    public Position getStartPos(){
 	   return startPos;
    }

    /**
     * Method to retrieve the ending position of the last scanned token.
     * @return the first position beyond the last scanned token.
     */
    public Position getEndPos(){
    	   return endPos;
    }

    /**
     * Method to retrieve the semantic value of the last scanned token.
     * @return the semantic value of the last scanned token.
     */
    public Object getLVal(){
        return lVal;
    }
    
  /**
   * Fetch the next token.  Called yylex in pull parsers.
   */
  public int yylex() throws IOException {
    startPos = new Position(yyline + 1, yycolumn);
    int ttype = nextToken();
    endPos = new Position(yyline + 1, yycolumn);
    return ttype;
  }

  /**
   * Build and emit a syntax error message.
   */
  public void reportSyntaxError(Parser.Context ctx) {
    System.err.print(ctx.getLocation() + ": syntax error");
      final int TOKENMAX = 10;
      Parser.SymbolKind[] arg = new Parser.SymbolKind[TOKENMAX];
      int n = ctx.getExpectedTokens(arg, TOKENMAX);
      for (int i = 0; i < n; ++i)
        System.err.print((i == 0 ? ": expected " : " or ")
                         + arg[i].getName());
      Parser.SymbolKind lookahead = ctx.getToken();
      if (lookahead != null)
        System.err.print(" before " + lookahead.getName());
    System.err.println("");
  }

  public void yyerror(Parser.Location loc, String msg) {
    if (loc == null)
      System.err.println(msg);
    else
      System.err.println(loc + ": " + msg);
  }

  public int token(int yytype){
	if (DEBUGGING) {
		System.err.printf ("*** token(%d): %s\n", yytype, yytext());
	}
	return yytype;
  }

  public int token(int yytype, Object lVal){
  	this.lVal = lVal;
  	return token(yytype);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ParserLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 176) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int nextToken() throws java.io.IOException, java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 98: break;
          case 2: 
            { return token(IDENTIFIER, yytext());
            }
          case 99: break;
          case 3: 
            { return token(NUMBER_INTEGER, new Integer(yytext()));
            }
          case 100: break;
          case 4: 
            { return token('.');
            }
          case 101: break;
          case 5: 
            { return token('-');
            }
          case 102: break;
          case 6: 
            { return token('/');
            }
          case 103: break;
          case 7: 
            { return token('*');
            }
          case 104: break;
          case 8: 
            { return token('{');
            }
          case 105: break;
          case 9: 
            { return token('}');
            }
          case 106: break;
          case 10: 
            { return token('(');
            }
          case 107: break;
          case 11: 
            { return token(')');
            }
          case 108: break;
          case 12: 
            { return token('[');
            }
          case 109: break;
          case 13: 
            { return token(']');
            }
          case 110: break;
          case 14: 
            { return token('<');
            }
          case 111: break;
          case 15: 
            { return token('>');
            }
          case 112: break;
          case 16: 
            { return token(',');
            }
          case 113: break;
          case 17: 
            { return token(':');
            }
          case 114: break;
          case 18: 
            { return token(';');
            }
          case 115: break;
          case 19: 
            { return token('!');
            }
          case 116: break;
          case 20: 
            { return token('+');
            }
          case 117: break;
          case 21: 
            { return token('%');
            }
          case 118: break;
          case 22: 
            { return token('&');
            }
          case 119: break;
          case 23: 
            { return token('|');
            }
          case 120: break;
          case 24: 
            { return token(DOTS);
            }
          case 121: break;
          case 25: 
            { return token(MINUS_MINUS);
            }
          case 122: break;
          case 26: 
            { return token(MINUS_ASSIGN);
            }
          case 123: break;
          case 27: 
            { return token(LITTERAL_STRING, yytext());
            }
          case 124: break;
          case 28: 
            { System.err.println("*** comments");
            }
          case 125: break;
          case 29: 
            { return token(DIV_ASSIGN);
            }
          case 126: break;
          case 30: 
            { return token(token(TIMES_ASSIGN));
            }
          case 127: break;
          case 31: 
            { return token(LT_LT);
            }
          case 128: break;
          case 32: 
            { return token(LT_EQ);
            }
          case 129: break;
          case 33: 
            { return token(GT_GT);
            }
          case 130: break;
          case 34: 
            { return token(GT_EQ);
            }
          case 131: break;
          case 35: 
            { return token(ASSIGN);
            }
          case 132: break;
          case 36: 
            { return token(BANG_EQ);
            }
          case 133: break;
          case 37: 
            { return token(PLUS_PLUS);
            }
          case 134: break;
          case 38: 
            { return token(PLUS_ASSIGN);
            }
          case 135: break;
          case 39: 
            { return token(PERC_ASSIGN);
            }
          case 136: break;
          case 40: 
            { return token(AMP_AMP);
            }
          case 137: break;
          case 41: 
            { return token(AMP_ASSIGN);
            }
          case 138: break;
          case 42: 
            { return token(PIPE_PIPE);
            }
          case 139: break;
          case 43: 
            { return token(PIPE_ASSIGN);
            }
          case 140: break;
          case 44: 
            { return token(EQ_EQ);
            }
          case 141: break;
          case 45: 
            { return token(IN);
            }
          case 142: break;
          case 46: 
            { return token(IF);
            }
          case 143: break;
          case 47: 
            { return token(DO);
            }
          case 144: break;
          case 48: 
            { return token(NUMBER_FLOAT, new Float(yytext()));
            }
          case 145: break;
          case 49: 
            { return token(LITTERAL_CHAR, yytext());
            }
          case 146: break;
          case 50: 
            { return token(LT_LT_ASSIGN);
            }
          case 147: break;
          case 51: 
            { return token(GT_GT_ASSIGN);
            }
          case 148: break;
          case 52: 
            { return token(AMP_AMP_ASSIGN);
            }
          case 149: break;
          case 53: 
            { return token(PIPE_PIPE_ASSIGN);
            }
          case 150: break;
          case 54: 
            { return token(SET);
            }
          case 151: break;
          case 55: 
            { return token(MAP);
            }
          case 152: break;
          case 56: 
            { return token(FOR);
            }
          case 153: break;
          case 57: 
            { return token(LIST);
            }
          case 154: break;
          case 58: 
            { return token(ELSE);
            }
          case 155: break;
          case 59: 
            { return token(ENUM);
            }
          case 156: break;
          case 60: 
            { return token(NEW);
            }
          case 157: break;
          case 61: 
            { return token(NULL);
            }
          case 158: break;
          case 62: 
            { return token(CASE);
            }
          case 159: break;
          case 63: 
            { return token(CHAR);
            }
          case 160: break;
          case 64: 
            { return token(MAIN);
            }
          case 161: break;
          case 65: 
            { return token(THIS);
            }
          case 162: break;
          case 66: 
            { return token(TYPE);
            }
          case 163: break;
          case 67: 
            { return token(BREAK);
            }
          case 164: break;
          case 68: 
            { return token(RANGE);
            }
          case 165: break;
          case 69: 
            { return token(CONST);
            }
          case 166: break;
          case 70: 
            { return token(CLASS);
            }
          case 167: break;
          case 71: 
            { return token(FLOAT);
            }
          case 168: break;
          case 72: 
            { return token(FINAL);
            }
          case 169: break;
          case 73: 
            { return token(WRITE);
            }
          case 170: break;
          case 74: 
            { return token(WHILE);
            }
          case 171: break;
          case 75: 
            { return token(READLN);
            }
          case 172: break;
          case 76: 
            { return token(RETURN);
            }
          case 173: break;
          case 77: 
            { return token(STRING);
            }
          case 174: break;
          case 78: 
            { return token(SWITCH);
            }
          case 175: break;
          case 79: 
            { return token(PUBLIC);
            }
          case 176: break;
          case 80: 
            { return token(IMPORT);
            }
          case 177: break;
          case 81: 
            { return token(BOOLEAN);
            }
          case 178: break;
          case 82: 
            { return token(PRIVATE);
            }
          case 179: break;
          case 83: 
            { return token(INTEGER);
            }
          case 180: break;
          case 84: 
            { return token(DEFAULT);
            }
          case 181: break;
          case 85: 
            { return token(VIRTUAL);
            }
          case 182: break;
          case 86: 
            { return token(FOREACH);
            }
          case 183: break;
          case 87: 
            { return token(WRITELN);
            }
          case 184: break;
          case 88: 
            { return token(OPERATOR);
            }
          case 185: break;
          case 89: 
            { return token(EXTENDS);
            }
          case 186: break;
          case 90: 
            { return token(CONTINUE);
            }
          case 187: break;
          case 91: 
            { return token(FUNCTION);
            }
          case 188: break;
          case 92: 
            { return token(PROCEDURE);
            }
          case 189: break;
          case 93: 
            { return token(PROTECTED);
            }
          case 190: break;
          case 94: 
            { return token(INTERFACE);
            }
          case 191: break;
          case 95: 
            { return token(EQUIVALENT);
            }
          case 192: break;
          case 96: 
            { return token(COMPARABLE);
            }
          case 193: break;
          case 97: 
            { return token(IMPLEMENTS);
            }
          case 194: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
